### ISSUE TITLE
Double frequency issue when recording

### ISSUE THREAD

**Issue by brivbl** [loggerhead-instruments/snap#20]
Hello,

I tried compiling the source code on a loggerhead snap card to record a 1kHz sine signal. When I analyze the output .wav file with audacity, I get a 2kHz sine signal. (.wav header parameters were unchanged, 1 channel, 16 bits per sample, 44.1kHz samplerate).

But when I use the latest hex file available, I can get a 1kHz .wav signal without any problem.

Do you have an idea where this issue can come from ? I tried re-installing the teensy Audio.h library, but no success.

thank you.

**Comment by davidallenmann** [comment]
Are you using the audio library from here:
https://github.com/loggerhead-instruments/libraries/tree/master/snap_libraries

**Comment by WMXZ-EU** [comment]
Could you also indicate, which F_CPU you were setting for compilation?

**Comment by brivbl** [comment]
Thanks for the library suggestion, I just installed them now and it works perfectly.

Also I was using the 72 MHz compilation frequency.
